CREATE TABLE `option_config` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(150) NOT NULL DEFAULT '' COMMENT '类型' COLLATE 'utf8mb4_bin',
	`label` VARCHAR(150) NOT NULL DEFAULT '0' COMMENT '名称' COLLATE 'utf8mb4_bin',
	`value` VARCHAR(150) NOT NULL DEFAULT '0' COMMENT '值' COLLATE 'utf8mb4_bin',
	`yn` INT(10) NOT NULL DEFAULT '0' COMMENT '状态 1: 启用, 0: 禁用',
	`creator_id` BIGINT(19) NOT NULL DEFAULT '0' COMMENT '创建人ID',
	`creator_name` VARCHAR(150) NULL DEFAULT NULL COMMENT '创建人名称' COLLATE 'utf8mb4_bin',
	`created` DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '创建时间',
	`modifier_id` BIGINT(19) NOT NULL COMMENT '更新人ID',
	`modifier_name` VARCHAR(150) NULL DEFAULT NULL COMMENT '更新人名称' COLLATE 'utf8mb4_bin',
	`modified` DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP' ON UPDATE (CURRENT_TIMESTAMP) COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `uq_type_lable` (`type`, `label`) USING BTREE
)
COMMENT='选项配置'
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;
